### ISSUE TITLE
can't scroll w/ Firefox

### ISSUE THREAD

**Issue by bugrasan** [azurecitadel/azurecitadel#104]
**Bug exists on page**
on any page, for testing purpose this can be used https://www.azurecitadel.com/ai/

**Describe the bug**
the scrollbar is not visible, nor can the page be scrolled with arrow keys or mouse wheel

**To Reproduce**
1. Go to page above with firefox (linux or windows)
2. try to scroll
3. See error

**Expected behavior**
the page should be scrollable as such properly visible on firefox

**Comment by dholbert** [comment]
Hi folks! Firefox engineer here.  We investigated this in https://bugzilla.mozilla.org/show_bug.cgi?id=1776598 and determined it to be a case where the site is accidentally depending on a historical WebKit quirks-mode-only behavior.  Chrome/Safari actually agree with Firefox on the clipped/broken rendering, if I force the page to render in standards mode (by adding a `<!DOCTYPE html>` which is best-practice these days).

The fix should be pretty simple -- you've got a `<main>` element on each page whose height you're constraining with `style="height:-webkit-fill-available"`.  If you change that `main` element to `height: 100%` or `height: 100vh`, it doesn't seem to change the behavior in Chrome/Safari (good) and it fixes the issue in Firefox, by using a more standards-compliant way to fill the viewport there.

**Comment by ojt** [comment]
As mentioned by @dholbert above, the fix is very easy. Get rid of the inline CSS in the three container elements, and change it to `height: 100%;`. I see absolutely no reason for the fill-available rule there, much less for use of non-standard or poorly supported rules. And quite honestly on a page like that with the content it has I do not see any reason to use `overflow: hidden` on the `body` element. It is a text heavy site, not an immersive SPA. I'm trying not to get into the discussion of "works best in Chrome" but hopefully the message came through. Use the standards. Keep it simple.

**Comment by aviita** [comment]
Seems there was some theme related issue reported earlier, but do not know which theme the Citadel uses.

**Comment by abdulmohsin** [comment]
The documentation is still not working correctly in Firefox , pls note there is no scroll-bar in right to view the content

![image](https://user-images.githubusercontent.com/506948/194236678-810c6a3b-3a57-4b8a-853b-d090e20fa8ca.png)

**Comment by richeney** [comment]
Apologies for taking so long - that was an easy fix. Thanks @dholbert for the detail.

**Comment by richeney** [comment]
Also took your advice @ojt as a separate commit in case any unexpected issues crop up.

Thanks again to everyone who took the time to comment!
